server:
  port: 8003
spring:
  application:
    name: admin
  boot:
    admin:
      discovery:
        ignored-services:
      client:
        instance:
          prefer-ip: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/"
  endpoint:
    health:
      show-details: always
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
