server:
  port: 8001
spring:
  application:
    name: server

eureka:
  instance:
    hostname: localhost
    health-check-url-path: /actuator/health
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

